apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sandeep-deploy
  name: sandeep-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sandeep-deploy
  template:
    metadata:
      labels:
        app: sandeep-deploy
    spec:
      containers:
      - image: cloudsihmar/new-pet:11
        name: pet
