apiVersion: v1
kind: Service
metadata:
  labels:
    app: pet-deploy
  name: sandeep-svc
  #namespace: pet
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sandeep-deploy
  type: NodePort
